FROM golang:1.25-bullseye

ENV GO111MODULE=on
ENV CGO_ENABLED=1
ENV GOPROXY=https://goproxy.cn,direct
ENV GOCACHE=/gocache/cache
ENV GOMODCACHE=/gocache/mod_cache
ENV GOPATH=/gocache/path

RUN apt update && \
        apt install -y --no-install-recommends binutils-aarch64-linux-gnu \
            gcc-aarch64-linux-gnu \
            binutils-mingw-w64 \
            gcc-mingw-w64-x86-64 \
            libluajit-5.1-dev \
            libc6-dev-arm64-cross && \
        apt clean && \
        rm -rf /var/lib/apt/lists/*

COPY ./loong-gcc8 /usr/local/loong/gcc
COPY ./loong-gcc15 /usr/local/loongnix23.1
COPY ./loong-go /usr/local/loong/go

WORKDIR /app
