name: Build ffmpeg-rockchip-arm64

permissions:
  id-token: write
  attestations: write
  artifact-metadata: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdrm-dev cmake meson ninja-build pkg-config
          mkdir -p build

      - name: Build MPP
        run: |
          git clone -b jellyfin-mpp --depth=1 https://github.com/nyanmisaka/mpp.git rkmpp
          pushd rkmpp
          mkdir rkmpp_build
          pushd rkmpp_build
          cmake \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_INSTALL_LIBDIR=lib \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DBUILD_TEST=ON \
            ..
          make -j $(nproc)
          make install DESTDIR=../../build   # 安装到 ./build/usr
          popd
          popd

      - name: Build RGA
        run: |
          git clone -b jellyfin-rga --depth=1 https://github.com/nyanmisaka/rk-mirrors.git rkrga
          meson setup rkrga rkrga_build \
            --prefix=/usr \
            --libdir=lib \
            --buildtype=release \
            --default-library=shared \
            -Dcpp_args=-fpermissive \
            -Dlibdrm=false \
            -Dlibrga_demo=false
          ninja -C rkrga_build
          DESTDIR=$PWD/build ninja -C rkrga_build install   # 明确指定 DESTDIR

      - name: Build FFmpeg
        run: |
          export PKG_CONFIG_PATH="$PWD/build/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
          git clone --depth=1 https://github.com/nyanmisaka/ffmpeg-rockchip.git ffmpeg
          pushd ffmpeg
          ./configure \
            --prefix=/usr \
            --enable-gpl \
            --enable-version3 \
            --enable-libdrm \
            --enable-rkmpp \
            --enable-rkrga \
            --extra-cflags="-I$PWD/../build/usr/include" \
            --extra-ldflags="-L$PWD/../build/usr/lib"
          make -j $(nproc)
          ./ffmpeg -decoders | grep rkmpp
          ./ffmpeg -encoders | grep rkmpp
          ./ffmpeg -filters | grep rkrga
          make install DESTDIR=../build
          popd

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ffmpeg-rockchip-arm64
          path: ./build