name: Build ffmpeg-rockchip-arm64

permissions:
  id-token: write
  attestations: write
  artifact-metadata: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: install dependency
        run: sudo apt-get update && apt-get install -y libdrm-dev cmake meson ninja-build pkg-config && mkdir build

      - name: build MPP
        run: |
          git clone -b jellyfin-mpp --depth=1 https://gitee.com/nyanmisaka/mpp.git rkmpp
          pushd rkmpp
          mkdir rkmpp_build
          pushd rkmpp_build
          cmake \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DBUILD_TEST=ON \
            ..
          make -j $(nproc)
          make install DESTDIR=../../build
          popd
          popd

      - name: Build RGA
        env: DESTDIR=bulid
        run: |
          git clone -b jellyfin-rga --depth=1 https://gitee.com/nyanmisaka/rga.git rkrga
          meson setup rkrga rkrga_build \
            --prefix=/usr \
            --libdir=lib \
            --buildtype=release \
            --default-library=shared \
            -Dcpp_args=-fpermissive \
            -Dlibdrm=false \
            -Dlibrga_demo=false
          meson configure rkrga_build
          ninja -C rkrga_build install

      - name: Build the minimal FFmpeg
        run: |
          git clone --depth=1 https://github.com/nyanmisaka/ffmpeg-rockchip.git ffmpeg
          pushd ffmpeg
          ./configure --prefix=/usr --enable-gpl --enable-version3 --enable-libdrm --enable-rkmpp --enable-rkrga
          make -j $(nproc)
          ./ffmpeg -decoders | grep rkmpp
          ./ffmpeg -encoders | grep rkmpp
          ./ffmpeg -filters | grep rkrga

          make install DESTDIR=../build
          popd
                
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: pgsimcity
          path: ./build
