name: build cross-compile docker images

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Create Necessary Directory
              run: mkdir cross-compile/loong-gcc8 cross-compile/loong-gcc15 cross-compile/loong-go

            - name: Download LoongArch64 GCC 8.3.0 Cross Toolchain
              run: |
                curl -fsSL https://ftp.loongnix.cn/toolchain/gcc/release/loongarch/gcc8/loongson-gnu-toolchain-8.3-x86_64-loongarch64-linux-gnu-rc1.6.tar.xz \
                  | tar -Jxv -C cross-compile/loong-gcc8 --strip-components=1

            - name: Download LoongArch64 GCC 15.1.0 Cross Toolchain
              run: |
                curl -fsSL https://github.com/loongson/build-tools/releases/download/2025.08.08/x86_64-cross-tools-loongarch64-binutils_2.45-gcc_15.1.0-glibc_2.42.tar.xz \
                  | tar -Jxv -C cross-compile/loong-gcc15 --strip-components=1

            - name: Download LoongArch64 Go 24.6
              run: |
                curl -fsSL https://ftp.loongnix.cn/toolchain/golang/go-1.24/abi1.0/go1.24.11.linux-amd64.tar.gz \
                  | tar -zxv -C cross-compile/loong-go --strip-components=1
            
            - name: Build Docker image
              run: |
                docker build \
                  -f cross-compile\Dockerfile \
                  -t cross-compile:$(date "+%Y%d%m") \
                  cross-compile

            - name: Save and compress image
              run: |
                docker save cross-compile:$(date "+%Y%d%m") | gzip > cross-compile_$(date "+%Y%d%m").tar.gz

            - name: Create Release and Upload Asset
              uses: softprops/action-gh-release@v1
              with:
                tag_name: cross-compile_$(date "+%Y%d%m")
                name: Release for cross-compile:$(date "+%Y%d%m")
                body: |
                    Docker image built from ${{ github.event.inputs.dockerfile_path }}
                    Generated by workflow run #${{ github.run_number }}
                    Build With:
                    - LoongArch64 GCC 8.3.0 Cross Toolchain
                    - LoongArch64 GCC 15.1.0 Cross Toolchain
                    - LoongArch64 Go 24.6
                files: cross-compile_$(date "+%Y%d%m").tar.gz
                generate_release_notes: true

              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}